<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.0.RELEASE</version>
	</parent>

	<groupId>DataMigrationProgram</groupId>
	<artifactId>DataMigrationProgram</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>DataMigrationProgram</name>
	<!-- <url>https://www.nets.com.sg/</url> -->

	<properties>
 	<java.version>11</java.version> 
		
		<!-- <maven.test.skip>true</maven.test.skip> -->
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
			<version>6.10.0</version>
		</dependency>
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports-fonts</artifactId>
			<version>6.10.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-envers</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-beanutils</groupId>
			<artifactId>commons-beanutils</artifactId>
			<version>1.9.4</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>ooxml-schemas</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>commons-net</groupId>
			<artifactId>commons-net</artifactId>
			<version>3.6</version>
		</dependency>
		<dependency>
			<groupId>javax.persistence</groupId>
			<artifactId>javax.persistence-api</artifactId>
			<version>2.2</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.20</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.lowagie</groupId>
			<artifactId>itext</artifactId>
			<version>2.1.7</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/junit/junit -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8.1</version>
			<scope>test</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.mockito/mockito-all -->
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>1.10.19</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<version>1.4.200</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
<!-- https://mvnrepository.com/artifact/com.jcraft/jsch -->
<dependency>
    <groupId>com.jcraft</groupId>
    <artifactId>jsch</artifactId>
    <version>0.1.55</version>
</dependency>

	</dependencies>

	<profiles>
		<profile>
			<id>dev</id>
		</profile>
		<profile>
			<id>nets</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<!-- <repositories> <repository> <id>Central</id> <name>InternalMirrorofCentralRepository</name> 
				<url>http://artifacts.nets.com.sg:8071/repository/nets-proxy/</url> <snapshots> 
				<enabled>false</enabled> </snapshots> </repository> <repository> <id>nets-internal</id> 
				<url>http://artifacts.nets.com.sg:8071/repository/nets-internal/ </url> </repository> 
				<repository> <id>nets-releases-repo</id> <url>http://artifacts.nets.com.sg:8071/repository/nets-releases/ 
				</url> <releases> <enabled>true</enabled> </releases> <snapshots> <enabled>false</enabled> 
				</snapshots> </repository> <repository> <id>nets-snapshots-repo</id> <url>http://artifacts.nets.com.sg:8071/repository/nets-snapshots/ 
				</url> <releases> <enabled>false</enabled> </releases> <snapshots> <enabled>true</enabled> 
				</snapshots> </repository> </repositories> <distributionManagement> <repository> 
				<id>nets-ns-rtgs-releases</id> <url>http://artifacts.nets.com.sg:8071/repository/nets-ns-rtgs-releases/ 
				</url> </repository> <snapshotRepository> <id>nets-ns-rtgs-snapshots</id> 
				<url>http://artifacts.nets.com.sg:8071/repository/nets-ns-rtgs-snapshots/ 
				</url> </snapshotRepository> </distributionManagement> -->
			<distributionManagement>
				<repository>
					<id>Central Maven repository</id>
					<name>Central Maven repository https</name>
					<url>https://repo.maven.apache.org/maven2</url>
				</repository>
				<!-- https://mvnrepository.com/artifact/com.lowagie/itext -->
			</distributionManagement>
		</profile>
	</profiles>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.jacoco</groupId>
					<artifactId>jacoco-maven-plugin</artifactId>
					<version>0.8.5</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>**/LoadPublicAndPrivateKeyService.class</exclude>
						<exclude>**/VerifySignatureService.class</exclude>
						<exclude>**/exception./*</exclude>
					</excludes>
				</configuration>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<dependencies>
					<dependency>
						<groupId>org.junit.platform</groupId>
						<artifactId>junit-platform-surefire-provider</artifactId>
						<version>1.1.0</version>
					</dependency>
					<dependency>
						<groupId>org.junit.jupiter</groupId>
						<artifactId>junit-jupiter-engine</artifactId>
						<version>5.1.0</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>

	</build>
	<!-- <pluginRepositories> <pluginRepository> <id>nets-central</id> <name>InternalMirrorofCentralRepository</name> 
		<url>http://artifacts.nets.com.sg:8071/repository/nets-proxy/</url> <snapshots> 
		<enabled>false</enabled> </snapshots> </pluginRepository> <pluginRepository> 
		<id>nets-internal</id> <url>http://artifacts.nets.com.sg:8071/repository/nets-internal/ 
		</url> </pluginRepository> <pluginRepository> <id>nets-releases-repo</id> 
		<url>http://artifacts.nets.com.sg:8071/repository/nets-releases/ </url> <releases> 
		<enabled>true</enabled> </releases> <snapshots> <enabled>false</enabled> 
		</snapshots> </pluginRepository> <pluginRepository> <id>nets-snapshots-repo</id> 
		<url>http://artifacts.nets.com.sg:8071/repository/nets-snapshots/ </url> 
		<releases> <enabled>false</enabled> </releases> <snapshots> <enabled>true</enabled> 
		</snapshots> </pluginRepository> </pluginRepositories> -->
	<pluginRepositories>
		<pluginRepository>
			<id>central</id>
			<name>Central Repository</name>
			<url>https://repo.maven.apache.org/maven2</url>
			<layout>default</layout>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<releases>
				<updatePolicy>never</updatePolicy>
			</releases>
		</pluginRepository>
	</pluginRepositories>
	<repositories>
		<repository>
			<id>central</id>
			<name>Central Repository</name>
			<url>https://repo.maven.apache.org/maven2</url>
			<layout>default</layout>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>central2</id>
			<name>Central Repository 2</name>
			<url>https://mvnrepository.com/artifact/com.lowagie/itext</url>
			<layout>default</layout>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
</project>