server.port=9095
# processor data
application.type=DataMigration
application.processorType=DM
application.processorId=dm101
application.testEnvironment=true
spring.main.allow-bean-definition-overriding=true
server.servlet.context-path=/dataMigration

logging.level.*=DEBUG
logging.file.name=./logs/datamigration_app.log
logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n
spring.datasource.jdbcUrl=jdbc:mysql://103.177.224.100:3306/sss_nets_mig?allowPublicKeyRetrieval=true&useSSL=false
#sss_nets_mig
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=test123
spring.datasource.password=test123

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true

report.savePath=./reports/

spring.h2.console.enabled=true

