


#FTP.ENABLE = (y or n) ,y can read file from ftp path ,n can read files from MigrationFiles folder.
FTP.IP_ADDRESS = 192.168.100.13
FTP.ENABLED = n
FTP.USER_NAME = tester
FTP.PASSWORD = password
FTP.PORT = 2222
FTP.FILE_PATH = /
FILE_DELIMITER = |
#MEMBER_FILE_UPLOAD.IP_ADDRESS = 103.177.224.100
#MEMBER_FILE_UPLOAD.FILE_PATH = E:\\DataMigrationBat\\DataMigrationService\\MigrationFiles\\
#MEMBER_FILE_UPLOAD.FILE_NAME =Member.txt
#MEMBER_FILE_UPLOAD.LIVE_TABLE_NAME = MEMBER
#MEMBER_FILE_UPLOAD.FILE_DELIMITER = |

#RTGS_FILE_PATH = /sts/file
#SSS_FILE_PATH 

ACCOUNT_FILE_UPLOAD.FILE_NAME = ACCOUNT_FILE_UPLOAD.txt
ACCOUNT_FILE_UPLOAD.LIVE_TABLE_NAME = account


ACCOUNT_POSITION_FILE_UPLOAD.FILE_NAME =ACCOUNT_POSITION_FILE_UPLOAD.txt
ACCOUNT_POSITION_FILE_UPLOAD.LIVE_TABLE_NAME = account_position


CBM_COST_CENTRE_FILE_UPLOAD.FILE_NAME = CBM_COST_CENTRE_FILE_UPLOAD.txt
CBM_COST_CENTRE_FILE_UPLOAD.LIVE_TABLE_NAME =cbm_cost_centre


CBM_DEPOSIT_RATE_FILE_UPLOAD.FILE_NAME =CBM_DEPOSIT_RATE_FILE_UPLOAD.txt
CBM_DEPOSIT_RATE_FILE_UPLOAD.LIVE_TABLE_NAME =cbm_deposit_rate


CBM_GL_ACCOUNT_FILE_UPLOAD.FILE_NAME =CBM_GL_ACCOUNT_FILE_UPLOAD.txt
CBM_GL_ACCOUNT_FILE_UPLOAD.LIVE_TABLE_NAME = cbm_gl_account

CBM_FLOATING_RATE_FILE_UPLOAD.FILE_NAME =CBM_FLOATING_RATE_FILE_UPLOAD.txt
CBM_FLOATING_RATE_FILE_UPLOAD.LIVE_TABLE_NAME = cbm_floating_rate

CBM_LIABILITIES_BASE_FILE_UPLOAD.FILE_NAME =CBM_LIABILITIES_BASE_FILE_UPLOAD.txt
CBM_LIABILITIES_BASE_FILE_UPLOAD.LIVE_TABLE_NAME =cbm_liabilities_base

CBM_LIABILITIES_BASE_DETAIL_FILE_UPLOAD.FILE_NAME =CBM_LIABILITIES_BASE_DETAIL_FILE_UPLOAD.txt
CBM_LIABILITIES_BASE_DETAIL_FILE_UPLOAD.LIVE_TABLE_NAME =cbm_liabilities_base_detail

SSS_ALLOTMENT_FILE_UPLOAD.FILE_NAME = SSS_ALLOTMENT_FILE_UPLOAD.txt
SSS_ALLOTMENT_FILE_UPLOAD.LIVE_TABLE_NAME =allotment

SSS_FLOATING_RATE_FILE_UPLOAD.FILE_NAME = SSS_FLOATING_RATE_FILE_UPLOAD.txt
SSS_FLOATING_RATE_FILE_UPLOAD.LIVE_TABLE_NAME = sss_floating_rates

SSS_SECURITIES_CODE_FILE_UPLOAD.FILE_NAME =SSS_SECURITIES_CODE_FILE_UPLOAD.txt
SSS_SECURITIES_CODE_FILE_UPLOAD.LIVE_TABLE_NAME =securities_code
STEPUP_FILE_NAME=stepup.txt

SSS_SECURITIES_CODE_STATISTICS_FILE_UPLOAD.FILE_NAME =SSS_SECURITIES_CODE_STATISTICS_FILE_UPLOAD.txt
SSS_SECURITIES_CODE_STATISTICS_FILE_UPLOAD.LIVE_TABLE_NAME =sss_securities_code_statistics

SSS_SECURITIES_POSITION_STATS_FILE_UPLOAD.FILE_NAME = SSS_SECURITIES_POSITION_STATS_FILE_UPLOAD.txt
SSS_SECURITIES_POSITION_STATS_FILE_UPLOAD.LIVE_TABLE_NAME = sss_securities_position_stats

SSS_SECURITIES_PRICE_FILE_UPLOAD.FILE_NAME =SSS_SECURITIES_PRICE_FILE_UPLOAD.txt
SSS_SECURITIES_PRICE_FILE_UPLOAD.LIVE_TABLE_NAME =sss_securities_price

SSS_TRANSACTION_FILE_UPLOAD.FILE_NAME =SSS_TRANSACTION_FILE_UPLOAD.txt
SSS_TRANSACTION_FILE_UPLOAD.LIVE_TABLE_NAME =sss_transaction

#MEMBER_FILE_UPLOAD.TABLE_FIELD_NAMES=id|member_code|swift_bic|swift_member|bank_code|name|short_name|member_status|member_type|sector_id|mcb_id|uen|lei|member_classification|exempted_from_billing|exempted_from_system_limit|location|activation_date|action|status|approval_remark|workflow_status_id|fi_group|billing_profile_id|mcb_intraday|mcb_eod_minimum|mcb_eod_maximum|mcb_average|tax_profile_id|verified_by|verified_date
ACCOUNT_FILE_UPLOAD.TABLE_FIELD_NAMES=member_code|account_number|description|account_type|main_account_indicator|default_main_account|statement_delivery_bic|account_status|currency_code|end_of_day_statement|gl_category|cost_centre|gl_account_number|statement_interval
ACCOUNT_POSITION_FILE_UPLOAD.TABLE_FIELD_NAMES=account_id|currency_code|member_code|current_account_balance|opening_account_balance|available_balance|created_date
CBM_COST_CENTRE_FILE_UPLOAD.TABLE_FIELD_NAMES=cost_centre
CBM_DEPOSIT_RATE_FILE_UPLOAD.TABLE_FIELD_NAMES=tenor_period|deposit_rate
CBM_GL_ACCOUNT_FILE_UPLOAD.TABLE_FIELD_NAMES=gl_account|gl_account_description
CBM_FLOATING_RATE_FILE_UPLOAD.TABLE_FIELD_NAMES=reference_rate|publication_date|value_date|rate
CBM_LIABILITIES_BASE_FILE_UPLOAD.TABLE_FIELD_NAMES=member_code|currency_code|ql_lb_type|effective_date
CBM_LIABILITIES_BASE_DETAIL_FILE_UPLOAD.TABLE_FIELD_NAMES=member_code|start_date|end_date|ql_lb

#SSS_MEMBER_FILE_UPLOAD.TABLE_FIELD_NAMES=id|member_code|member_name|activation_date|member_short_name|member_status|member_type|sector_id|bank_code|auto_debit_indicator|location|facility_eligibility_id|lei|uen|zero_holdings_statement|exempted_from_billing|exempted_from_system_limit|statement_delivery_bic|tax_profile_id|fee_profile_id|end_of_day_statement
#SSS_ACCOUNT_FILE_UPLOAD.TABLE_FIELD_NAMES=id|account_id|member_code|custody_account_type_id|account_category|investor_individual_id|investor_name|account_status|tax_profile_id|statement_delivery_bic
SSS_ALLOTMENT_FILE_UPLOAD.TABLE_FIELD_NAMES=securities_code|auction_date|issuance_date|allotment_price|total_nominal_amount_to_be_alloted|first_allotment|total_settlement_amount|processed
SSS_FLOATING_RATE_FILE_UPLOAD.TABLE_FIELD_NAMES=reference_rate|publication_date|value_date|rate
SSS_SECURITIES_CODE_FILE_UPLOAD.TABLE_FIELD_NAMES=securities_code|issue_code|description|securities_status|currency_code|denomination|first_auction_date|first_issuance_date|first_issuance_amount|redemption_date|optional_redemption_date|redemption_price|optional_redemption_price|central_bank_applied_amount|coupon_payment_frequency|coupon_rate|average_yield|record_date_period|tenor_period|issue_price|issue_yield|first_coupon_date
SSS_SECURITIES_CODE_STATISTICS_FILE_UPLOAD.TABLE_FIELD_NAMES=securities_code|total_redeemed_amount|total_redeemed_amount_for_erf|outstanding_nominal_amount|next_coupon_date|last_coupon_date|next_index_end_date|amount_alloted_to_central_bank|amount_alloted_to_others|total_nominal_amount_issued_for_erf
SSS_SECURITIES_POSITION_STATS_FILE_UPLOAD.TABLE_FIELD_NAMES=securities_code|opening_nominal_amount|closing_nominal_amount|account_id
SSS_SECURITIES_PRICE_FILE_UPLOAD.TABLE_FIELD_NAMES=securities_code|pricing_date|price|issue_code
SSS_TRANSACTION_FILE_UPLOAD.TABLE_FIELD_NAMES=sss_reference|securities_code|transaction_type|settlement_date|trade_date|currency_code|settlement_amount|nominal_amount|deal_price|deliverer_member_code|receiver_member_code|transaction_reference|created_date|modified_date|receiver_member_swift_code|message_type|receiver_rtgs_member_code|deliverer_rtgs_member_code|deliverer_account_no|receiver_account_no|receiver_sender_id|deliverer_sender_id|accured_interest_amount
